package output

import (
	"fmt"
	"html"
	"io"
	"sort"
	"strings"
)

// HTMLFormatter implements the OutputFormatter interface for HTML output
type HTMLFormatter struct{}

// FormatDuplicates formats duplicate results as HTML
func (f *HTMLFormatter) FormatDuplicates(result *DuplicateResult, writer io.Writer) error {
	htmlContent := f.generateHTML(result)
	_, err := writer.Write([]byte(htmlContent))
	return err
}

// generateHTML creates the complete HTML document
func (f *HTMLFormatter) generateHTML(result *DuplicateResult) string {
	var sb strings.Builder

	sb.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Duplicate Files Report</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            padding: 30px;
        }
        h1 {
            color: #333;
            border-bottom: 2px solid #007acc;
            padding-bottom: 10px;
        }
        .no-duplicates {
            text-align: center;
            color: #666;
            font-size: 18px;
            padding: 40px;
        }
        .duplicate-group {
            margin-bottom: 30px;
            border: 1px solid #ddd;
            border-radius: 6px;
            overflow: hidden;
        }
        .group-header {
            background: #f8f9fa;
            padding: 15px 20px;
            border-bottom: 1px solid #ddd;
        }
        .group-hash {
            font-family: monospace;
            color: #007acc;
            font-weight: bold;
        }
        .group-size {
            color: #666;
            font-size: 14px;
        }
        .file-list {
            padding: 0;
            margin: 0;
        }
        .file-item {
            padding: 12px 20px;
            border-bottom: 1px solid #eee;
            display: flex;
            align-items: center;
        }
        .file-item:last-child {
            border-bottom: none;
        }
        .file-name {
            font-family: monospace;
            flex: 1;
        }
        .file-badge {
            background: #28a745;
            color: white;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 12px;
            font-weight: bold;
        }
        .file-badge.original {
            background: #007acc;
        }
        .file-badge.duplicate {
            background: #dc3545;
        }
        .summary {
            background: #e9ecef;
            padding: 15px;
            border-radius: 6px;
            margin-bottom: 20px;
        }
        .summary-stats {
            display: flex;
            gap: 20px;
        }
        .stat {
            font-weight: bold;
            color: #007acc;
        }
        .duplicate-group.collapsed .file-list {
            display: none;
        }
        .group-header::before {
            content: '▼';
            margin-right: 8px;
            transition: transform 0.2s;
        }
        .duplicate-group.collapsed .group-header::before {
            transform: rotate(-90deg);
        }
        .group-hash:hover {
            background-color: #e9ecef;
            border-radius: 3px;
            padding: 2px 4px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Duplicate Files Report</h1>`)

	if !result.Found {
		sb.WriteString(`
        <div class="no-duplicates">
            No duplicate files found.
        </div>`)
	} else {
		totalGroups := len(result.Groups)
		totalFiles := 0
		for _, group := range result.Groups {
			totalFiles += len(group.Files)
		}

		sb.WriteString(fmt.Sprintf(`
        <div class="summary">
            <div class="summary-stats">
                <span class="stat">%d duplicate groups found</span>
                <span class="stat">%d total duplicate files</span>
            </div>
        </div>`, totalGroups, totalFiles))

		for i, group := range result.Groups {
			sb.WriteString(f.generateGroupHTML(group, i+1))
		}
	}

	sb.WriteString(`
    </div>`)

	// Add footer with branding
	if result.Metadata != nil {
		flags := []string{}
		for _, f := range result.Metadata.Flags {
			flags = append(flags, fmt.Sprintf("%s=%s", f.Name, f.Value))
		}
		flagStr := strings.Join(flags, ", ")
		sb.WriteString(fmt.Sprintf(`
    <footer style="text-align: center; margin-top: 40px; color: #666; font-size: 14px;">
        Generated by %s %s v%s on %s<br>
        Flags: %s
    </footer>`,
			html.EscapeString(result.Metadata.ToolName),
			html.EscapeString(result.Metadata.SubCommand),
			html.EscapeString(result.Metadata.Version),
			html.EscapeString(result.Metadata.GeneratedAt),
			html.EscapeString(flagStr)))
	}

	sb.WriteString(`
    <script>
        (function() {
            // Feature detection for clipboard API
            var supportsClipboard = navigator && navigator.clipboard && navigator.clipboard.writeText;

            // Fallback for older browsers
            function fallbackCopyText(text) {
                var textArea = document.createElement("textarea");
                textArea.value = text;
                document.body.appendChild(textArea);
                textArea.focus();
                textArea.select();
                try {
                    document.execCommand('copy');
                } catch (err) {
                    console.warn('Fallback copy failed');
                }
                document.body.removeChild(textArea);
            }

            // Copy hash functionality
            function copyHash(event) {
                var hash = event.target.getAttribute('data-full-hash');
                var original = event.target.textContent;
                if (supportsClipboard) {
                    navigator.clipboard.writeText(hash).then(function() {
                        event.target.textContent = 'Copied!';
                        setTimeout(function() {
                            event.target.textContent = original;
                        }, 1000);
                    });
                } else {
                    fallbackCopyText(hash);
                    event.target.textContent = 'Copied!';
                    setTimeout(function() {
                        event.target.textContent = original;
                    }, 1000);
                }
            }

            // Collapsible groups functionality
            function toggleGroup(event) {
                // Only toggle if clicking on header, not on hash
                if (event.target.classList.contains('group-hash')) return;

                var group = event.currentTarget.closest('.duplicate-group');
                var fileList = group.querySelector('.file-list');
                var isCollapsed = fileList.style.display === 'none';

                fileList.style.display = isCollapsed ? 'block' : 'none';
                group.classList.toggle('collapsed', !isCollapsed);
            }

            // Initialize when DOM is ready
            document.addEventListener('DOMContentLoaded', function() {
                // Add click handlers for hashes
                var hashes = document.querySelectorAll('.group-hash');
                for (var i = 0; i < hashes.length; i++) {
                    hashes[i].addEventListener('click', copyHash);
                    hashes[i].style.cursor = 'pointer';
                    hashes[i].title = 'Click to copy hash';
                }

                // Add click handlers for group headers
                var headers = document.querySelectorAll('.group-header');
                for (var i = 0; i < headers.length; i++) {
                    headers[i].addEventListener('click', toggleGroup);
                    headers[i].style.cursor = 'pointer';
                }
            });
        })();
    </script>
</body>
</html>`)

	return sb.String()
}

// generateGroupHTML creates HTML for a single duplicate group
func (f *HTMLFormatter) generateGroupHTML(group DuplicateGroup, _ int) string {
	var sb strings.Builder

	// Sort files alphabetically
	files := make([]string, len(group.Files))
	copy(files, group.Files)
	sort.Strings(files)

	sizeStr := "unknown size"
	if group.Size >= 0 {
		sizeStr = fmt.Sprintf("%d bytes", group.Size)
	}

	hashDisplay := group.Hash
	if len(hashDisplay) > 12 {
		hashDisplay = hashDisplay[:12] + "..."
	}

	sb.WriteString(fmt.Sprintf(`
        <div class="duplicate-group">
            <div class="group-header">
                <span class="group-hash" data-full-hash="%s">%s</span>
                <span class="group-size">(%s)</span>
            </div>
            <ul class="file-list">`, html.EscapeString(group.Hash), html.EscapeString(hashDisplay), html.EscapeString(sizeStr)))

	for j, file := range files {
		badgeClass := "duplicate"
		badgeText := "DUPLICATE"
		if j == 0 {
			badgeClass = "original"
			badgeText = "ORIGINAL"
		}

		sb.WriteString(fmt.Sprintf(`
                <li class="file-item">
                    <span class="file-name">%s</span>
                    <span class="file-badge %s">%s</span>
                </li>`, html.EscapeString(file), badgeClass, badgeText))
	}

	sb.WriteString(`
            </ul>
        </div>`)

	return sb.String()
}
